---
name: module3_task0
"on":
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: build
        run: |
          cd module3_task0
          make help
