name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Position and execute
      run: |
        cd <directory>
        make help
