---
name: module3_task1
“on”:
  push:
    branches:
      - main
  schedule:
    - cron: “0 0 * * *”
jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Run the script setup.sh
        run: |
          cd module3_task1/
          sudo ./setup.sh
      - name: Build the app
        run: |
          cd module3_task1/
          make build
